version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    working_directory: ~/Tweeter
    executor: android/android

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
            key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Chmod permissions # this is to set proper permissions for Gradlew Dependencies.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
# After executing a run command, you can store its build report as a job artifact
      - run:
          name: Clean, build, and run tests, and static analysis checks on the App module
          command: ./gradlew :app:clean :app:build :app:spotlessCheck :app:test
      - store_artifacts:
            path: app/build/reports
      - store_test_results:
            path: app/build/test-results
      - run:
          name: Clean, build, and run tests, and static analysis checks on the Authentication module
          command: ./gradlew :features:authentication:clean :features:authentication:build :features:authentication:spotlessCheck :features:authentication:test
      - store_artifacts:
          path: features/authentication/build/reports
      - store_test_results:
          path: features/authentication/build/test-results
      - run:
          name: Clean, build, and run tests, and static analysis checks on the Navigation module
          command: ./gradlew :libraries:navigator:clean :libraries:navigator:build :libraries:navigator:spotlessCheck :libraries:navigator:test
      - store_artifacts:
          path: libraries/navigator/build/reports
      - store_test_results:
          path: libraries/navigator/build/test-results
